[theme]
base = "dark"
primaryColor = "#00DAF8"
backgroundColor = "#0B1326"
secondaryBackgroundColor = "#060E20"
textColor = "#BCC7DE"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
showSidebarNavigation = false
